# Generated by Django 5.0.7 on 2024-07-09 17:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_NAME', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Subject', models.CharField(max_length=25)),
                ('Message', models.TextField()),
                ('Passport_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PASSWORD', models.IntegerField()),
                ('DATE_JOINED', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOOL_NAME', models.CharField(max_length=25)),
                ('DESCRIPTION', models.TextField()),
                ('AVAILABILITY', models.BooleanField(default=False, verbose_name='Active Status')),
                ('Price_Per_Day', models.IntegerField()),
                ('Duration', models.CharField(max_length=25, verbose_name='Enter Duration of Rent')),
                ('Condition', models.CharField(max_length=25)),
                ('Equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.categorytable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_from', models.DateField()),
                ('Booking_to', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Credit card', 'Credit card'), ('Debit card', 'Debit card'), ('Digital wallet', 'Digital wallet')], max_length=25)),
                ('payment_status', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('Payment_date', models.DateField()),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('Comment', models.TextField()),
                ('Review_date', models.DateField(default=django.utils.timezone.now)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.user')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maintenance_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=25)),
                ('Maintenance_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=25)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_price', models.IntegerField()),
                ('Booking_from', models.DateField()),
                ('Booking_To', models.DateField()),
                ('Return_Date', models.DateField(null=True)),
                ('Is_Confirmed', models.BooleanField(default=False, verbose_name='Active Status')),
                ('Payment_status', models.BooleanField(default=False)),
                ('PICKUP_LOCATION', models.TextField()),
                ('RETURN_LOCATION', models.TextField()),
                ('DAMAGE_REPORT', models.CharField(max_length=25, null=True)),
                ('LATE_RETURN_PENALTY', models.IntegerField()),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField()),
                ('ADDRESS', models.TextField()),
                ('PHONE_NO', models.BigIntegerField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalHub.user')),
            ],
        ),
    ]
