# Generated by Django 5.0.7 on 2024-07-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentalHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
